---
title: "xwords"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(glue)
```

## data

```{r}
xwords <- read.csv("xwstats.csv")

names(xwords) <- tolower(names(xwords))
xwords$puzzle.date <- ymd(xwords$puzzle.date)
xwords$completed.datetime <- ymd_hms(xwords$completed.at..et.)

xwords <- xwords |>
  select(-completed.at..et., excluded) |>
  mutate(time.taken.m = time.taken/60,
         adjusted.time.m = adjusted.time/60,
         average.time.m = average.time/60,
         average.adjusted.time.m = average.adjusted.time/60,
         day.of.week = case_when(
            day.of.week == "Su" ~ "Sunday",
            day.of.week == "Mo" ~ "Monday",
            day.of.week == "Tu" ~ "Tuesday",
            day.of.week == "We" ~ "Wednesday",
            day.of.week == "Th" ~ "Thursday",
            day.of.week == "Fr" ~ "Friday",
            day.of.week == "Sa" ~ "Saturday")) 
  
xwords$day.of.week <- factor(xwords$day.of.week, 
                             levels = c("Sunday", "Monday", 
                                        "Tuesday", "Wednesday", 
                                        "Thursday", "Friday", 
                                        "Saturday"), 
                             ordered = T)

head(xwords)
```

unsolved

```{r}
xwords |>
  filter(solved == "False") |>
  select(completed.datetime, checks, reveals, day.of.week)
```

### descriptive stats

```{r}
min(xwords$puzzle.date)
min(xwords$completed.datetime)

max(xwords$puzzle.date)
max(xwords$completed.datetime)

```

### time taken

```{r}
xwords |>
  ggplot(aes(x = time.taken.m)) +
  geom_histogram()
```

crazy outlier

```{r}
xwords |>
  filter(time.taken.m > 600)
```

```{r}
xwords |>
  filter(time.taken.m < 600) |>
  ggplot(aes(x = time.taken.m)) +
  geom_histogram()
```

```{r}
xwords |>
  filter(!(time.taken.m > 600) & day.of.week != "Sunday") |>  # remove outlier. remove sundays
  ggplot(aes(x = time.taken.m)) +
  geom_histogram(aes(fill = day.of.week)) +
  facet_wrap(~day.of.week) +
  theme_bw()
```

percentages with density plot

```{r}
xwords |>
  filter(!(time.taken.m > 600) & day.of.week != "Sunday") |>  # remove outlier. remove sundays
  ggplot(aes(x = time.taken.m)) +
  geom_density(aes(fill = day.of.week)) +
  facet_wrap(~day.of.week) +
  labs(title = "")
  theme_light()
```

histo overall

```{r}
mindate <- as.Date(min(xwords$completed.datetime)) #earliest completion date
maxdate <- as.Date(max(xwords$completed.datetime)) #latest completion date

xwords |>
  filter(!(time.taken.m > 60) & day.of.week != "Su") |>  # remove outlier. remove sundays
  ggplot(aes(x = time.taken.m)) +
  geom_histogram(aes(fill = day.of.week)) +
  labs(title = "Distribution of NYT Xword Puzzle Solve Times", 
       subtitle = glue("Puzzles solved between {mindate} and {maxdate}"), 
       x = "Solve time in minutes",
       y = "Count", 
       fill = "Puzzle day of week") +
  theme_light()

ggsave("xword_solve_times_hist.jpeg", width = 9, height = 5, units = "in")

```

split by days with density plot

```{r}
xwords |>
  filter(!(time.taken.m > 600) & day.of.week != "Sunday") |>  # remove outlier. remove sundays
  ggplot(aes(x = time.taken.m)) +
  geom_density(aes(fill = day.of.week)) +
  labs(title = "Distribution of NYT Xword Puzzle Solve Times", 
       subtitle = glue("Puzzles solved between {mindate} and {maxdate}"), 
       x = "Solve time in minutes",
       y = "Density",
       fill = "Puzzle day of week") +
  theme_light()

ggsave("xword_solve_times_dist.jpeg", width = 9, height = 5, units = "in")
```

median
```{r}
xwords |>
  group_by(day.of.week) |>
  summarize(median_solvetime = median(time.taken.m),
            mean_solvetime = mean(time.taken.m))
```


### puzzle solving speeds over time

have gone down...

```{r}
xwords |>
  filter(!(time.taken.m > 600) & day.of.week != "Sunday") |>
  ggplot(aes(x = as.Date(completed.datetime), y = time.taken.m)) +
  geom_point() +
  geom_smooth(se = F, method = "lm") +
  labs(subtitle = "date completed vs. time taken")
```


```{r}
xwords <- xwords |>
  mutate(completed.daysfromstart = as.Date(completed.datetime) - as.Date(min(completed.datetime)))

lm <- lm(time.taken.m ~ completed.daysfromstart, data = xwords)
lm
```

for every additional day i spend about half a second less on average

but maybe only because i'm doing more mondays

```{r}
xwords |>
  filter(!(time.taken.m > 600) & day.of.week != "Sunday") |>
  ggplot(aes(x = as.Date(completed.datetime), y = time.taken.m, color = day.of.week)) +
  geom_point() +
  geom_smooth(se = F, method = "lm") +
  labs(subtitle = "date completed vs. time taken")
```
```{r}
xwords |>
  filter(!(time.taken.m > 600) & day.of.week != "Sunday" & 
           as.Date(completed.datetime) >= ymd("2024-11-01")) |>
  ggplot(aes(x = as.Date(completed.datetime), y = time.taken.m, color = day.of.week)) +
  geom_line(linewidth = 1) 
```


by publishing date

```{r}
xwords |>
  filter(!(time.taken.m > 600) & day.of.week != "Sunday") |>
  ggplot(aes(x = puzzle.date, y = time.taken.m, color = day.of.week)) +
  geom_point() +
  labs(subtitle = "date of publication vs. time taken")


```

### how many puzzles was i doing over time?

```{r}
annots <- tibble(
  label = c("Final semester\nof graduate school","Marriage and\nhoneymoon",
            "Seasonal\ndepression"),
  xmin = c(ymd("2024-01-20"), ymd("2024-07-20"), ymd("2024-11-01")),
  xmax = c(ymd("2024-05-15"), ymd("2024-08-01"), ymd("2025-01-30"))
)

xwords |>
  ggplot(aes(x = as.Date(completed.datetime), fill = day.of.week)) +
  annotate("rect", xmin = annots$xmin[1:3],
           xmax = annots$xmax[1:3],
           ymin = 0, ymax = 24,
           alpha = 0.5, fill = "grey") +
  annotate("text", label = annots$label[1:3], 
           x = annots$xmin[1:3],
           y = 23,
           color = "grey30",
           size = 3, 
           hjust = 0) +
  geom_histogram(binwidth = 7) +
  scale_x_date(date_breaks = "3 months", date_labels = "%b %G") +
  labs(title = "NYT Xword Puzzles Solved Over Time", 
       subtitle = glue("Puzzles solved between {mindate} and {maxdate}"),
       x = "Date completed",
       y = "Puzzles completed in a seven-day period",
       fill = "Day of puzzle") +
  theme_light()

ggsave("xword_solve_over_time.jpeg", width = 9, height = 5, units = "in")
```

```{r}

countbyweek <- xwords |>
  mutate(week.completed = week(completed.datetime) + 
           52*(year(completed.datetime)- min(year(completed.datetime)))) |>
  count(week.completed)

dfcounts <- data.frame(week.completed = min(countbyweek$week.completed):max(countbyweek$week.completed))

countbyweek <- dfcounts |>
  left_join(countbyweek, by = "week.completed") |>
  mutate(n = if_else(is.na(n), 0, n))

ggplot(countbyweek, aes(x = week.completed, y = n)) +
  geom_line() +
  geom_point()

```
